import 'features/character/model/init'
import 'features/game-old/model/init'
import 'features/game/model/init'
import 'features/app/model/init'
import 'features/me/model/init'
import 'features/card/model/init'
